In [2]:
import numpy as np

In [3]:
    lista = [1, 2, 3, 4]

In [4]:
np.array(lista)

array([1, 2, 3, 4])

In [6]:
np_lista = (np.array(lista))
np_lista

array([1, 2, 3, 4])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
arr = np.zeros((10, 10))

In [22]:
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [37]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [46]:
np.random.rand(5,4,3)

array([[[7.84856635e-06, 8.31116608e-01, 3.91518576e-01],
        [1.65155210e-01, 4.64449187e-01, 6.14533868e-01],
        [6.88089628e-01, 7.47457365e-01, 2.70385617e-01],
        [9.35938534e-01, 3.80672089e-01, 9.44985239e-02]],

       [[7.60463207e-01, 6.62422110e-01, 9.12781427e-01],
        [5.01158421e-01, 7.42623136e-01, 2.14668481e-01],
        [1.52983723e-01, 3.24840812e-01, 1.36132975e-02],
        [4.37676884e-01, 4.18457427e-01, 8.01838997e-01]],

       [[8.69220259e-02, 4.50624129e-01, 9.06618691e-01],
        [9.01793158e-01, 2.89663823e-01, 4.51203974e-01],
        [4.44010630e-01, 8.43723736e-01, 1.43567542e-02],
        [8.35244809e-01, 4.31478932e-01, 3.02766645e-01]],

       [[4.64463314e-01, 9.93548152e-01, 7.28424014e-01],
        [7.27153690e-01, 9.37944954e-01, 8.72227933e-01],
        [4.74173430e-01, 1.70540156e-01, 9.42383931e-01],
        [2.22679196e-01, 2.10361673e-01, 3.52338481e-01]],

       [[2.18204079e-01, 4.09151595e-01, 7.06795478e-01],
      

In [48]:
np.random.randint(1,2,3)

array([1, 1, 1])

In [55]:
np.random.randint(4,5,5)

array([4, 4, 4, 4, 4])

In [57]:
arr= np.random.rand(25)

In [69]:
print(arr)

[[0.87283462 0.83102601 0.59630502 0.80683948 0.48356174]
 [0.05221911 0.94535376 0.41345915 0.91355341 0.14808012]
 [0.22238812 0.64375123 0.57684498 0.01395019 0.99386812]
 [0.73088042 0.93243191 0.81061436 0.04038687 0.67118301]
 [0.52320601 0.80523188 0.88258646 0.54253954 0.06090303]]


In [65]:
arr = arr.reshape((5,5))

In [70]:
arr.shape

(5, 5)

In [73]:
arr.argmax()

14

In [75]:
arr

array([[0.87283462, 0.83102601, 0.59630502, 0.80683948, 0.48356174],
       [0.05221911, 0.94535376, 0.41345915, 0.91355341, 0.14808012],
       [0.22238812, 0.64375123, 0.57684498, 0.01395019, 0.99386812],
       [0.73088042, 0.93243191, 0.81061436, 0.04038687, 0.67118301],
       [0.52320601, 0.80523188, 0.88258646, 0.54253954, 0.06090303]])

In [77]:
#Próxima Aula