In [1]:
import numpy as np

In [2]:
arr = arr.arange(0,3,5)

NameError: name 'arr' is not defined

In [3]:
arr = np.arange(0,3,5)

In [4]:
arr

array([0])

In [5]:
arr = np.arange(0,20,5)

In [6]:
arr

array([ 0,  5, 10, 15])

In [8]:
arr = np.arange(0,100,5)

In [9]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [10]:
arr.shape

(20,)

In [11]:
arr.reshape(10,10)

ValueError: cannot reshape array of size 20 into shape (10,10)

In [12]:
arr.reshape(5,4)

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [13]:
arr * arr

array([   0,   25,  100,  225,  400,  625,  900, 1225, 1600, 2025, 2500,
       3025, 3600, 4225, 4900, 5625, 6400, 7225, 8100, 9025])

In [14]:
arr = arr.reshape(5,4)

In [15]:
arr * arr

array([[   0,   25,  100,  225],
       [ 400,  625,  900, 1225],
       [1600, 2025, 2500, 3025],
       [3600, 4225, 4900, 5625],
       [6400, 7225, 8100, 9025]])

In [16]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [17]:
arr ** 2

array([[   0,   25,  100,  225],
       [ 400,  625,  900, 1225],
       [1600, 2025, 2500, 3025],
       [3600, 4225, 4900, 5625],
       [6400, 7225, 8100, 9025]])

In [18]:
arr2 = arr.reshape(4,5).copy

In [19]:
arr2

<function ndarray.copy>

In [20]:
arr2 = arr.reshape(4,5).copy()

In [21]:
arr2

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [22]:
arr2 * arr

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

In [23]:
arr2.reshape(5,4)

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [24]:
arr2* arr

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

In [25]:
arr.shape

(5, 4)

In [26]:
arr2 = arr2.reshape(5,4)

In [33]:
arr2 * arr

array([[   0,   25,  100,  225],
       [ 400,  625,  900, 1225],
       [1600, 2025, 2500, 3025],
       [3600, 4225, 4900, 5625],
       [6400, 7225, 8100, 9025]])

In [ ]:
#Raiz

In [32]:
np.sqrt(arr)

array([[0.        , 2.23606798, 3.16227766, 3.87298335],
       [4.47213595, 5.        , 5.47722558, 5.91607978],
       [6.32455532, 6.70820393, 7.07106781, 7.41619849],
       [7.74596669, 8.06225775, 8.36660027, 8.66025404],
       [8.94427191, 9.21954446, 9.48683298, 9.74679434]])

In [ ]:
#Exponeciação

In [31]:
np.exp(arr)

array([[1.00000000e+00, 1.48413159e+02, 2.20264658e+04, 3.26901737e+06],
       [4.85165195e+08, 7.20048993e+10, 1.06864746e+13, 1.58601345e+15],
       [2.35385267e+17, 3.49342711e+19, 5.18470553e+21, 7.69478527e+23],
       [1.14200739e+26, 1.69488924e+28, 2.51543867e+30, 3.73324200e+32],
       [5.54062238e+34, 8.22301271e+36, 1.22040329e+39, 1.81123908e+41]])

In [ ]:
#Média

In [30]:
np.mean(arr)

47.5

In [34]:
#Desvio Padrão

In [40]:
np.std(arr)

28.83140648667699

In [ ]:
#Seno

In [41]:
np.sin(arr)

array([[ 0.        , -0.95892427, -0.54402111,  0.65028784],
       [ 0.91294525, -0.13235175, -0.98803162, -0.42818267],
       [ 0.74511316,  0.85090352, -0.26237485, -0.99975517],
       [-0.30481062,  0.82682868,  0.77389068, -0.38778164],
       [-0.99388865, -0.17607562,  0.89399666,  0.68326171]])

In [ ]:
#Maximo

In [47]:
print("NP",np.max(arr))
print("Array",arr.max())

NP 95
Array 95


In [42]:
arr

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [ ]:
#Minimo

In [48]:
print("NP",np.min(arr))
print("Array",arr.min())

NP 0
Array 0
