In [4]:
import numpy as np

In [ ]:
#Criando um Array - arange cria um array arange(valorIni,valorFim, intervalo)

In [9]:
arr = np.arange(0,30,3)

In [84]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [ ]:
#Modos de pesquisa em um arange.

In [18]:
arr[3]

9

In [21]:
arr[2:5]

array([ 6,  9, 12])

In [24]:
arr[:7]

array([ 0,  3,  6,  9, 12, 15, 18])

In [25]:
#Pode ser usado para alterar valor, exemplo:

In [27]:
arr[5:] = 10

In [28]:
arr

array([ 0,  3,  6,  9, 12, 10, 10, 10, 10, 10])

In [29]:
#:)

In [30]:
#Criar um array e fazer um reshape para um matriz sempre proporcional, a área da matriz A*L 
# deve ser igual ao total do tamanho do array, exemplo:

In [32]:
arr = np.arange(50).reshape((5,10))

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [36]:
#Vizualizar o tamanho da matriz

In [37]:
arr.shape

(5, 10)

In [39]:
#Pesquisa em uma matriz Coluna->[][]<-Raiz 

In [45]:
arr[:4][:]

array([[ 4,  9,  5,  9,  9,  4,  5,  4,  9,  7],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
#Alterando matriz

In [43]:
arr[:1][:] = np.random.randint(4,10,10)

In [46]:
arr

array([[ 4,  9,  5,  9,  9,  4,  5,  4,  9,  7],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
#####################################IMPORTANTE#######################################

In [49]:
arr2 = arr

In [51]:
arr

array([[ 4,  9,  5,  9,  9,  4,  5,  4,  9,  7],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr2

array([[ 4,  9,  5,  9,  9,  4,  5,  4,  9,  7],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
arr[:1][:] = 100

In [55]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [56]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [ ]:
##### Pq arr2 pegou os valores de arr sendo que são variaveis diferentes?

In [57]:
##### Python entende que arr = arr2  -> arr2 é uma referencia de arr, ou seja um ponteiro para
######## arr, sendo assim tudo que for alterado em arr, será alterado em arr2 e vice versa

In [58]:
##### Como resolver?

In [59]:
arr2 = arr.copy()

In [60]:
#### Importante não vale apenas para a variavel arr copleta por exemplo se arr2 = arr[:1]
##### o valor alterado tanto em arr[:1] ou em arr será refletido.

In [63]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [ ]:
#FATIAR A MATRIZ - SUBMATRIZ

In [62]:
arr2[1:3,3:]

array([[13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [68]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [ ]:
#Fazer uma pesquisa com uma preposição <><><><><><><><><><><><><><><><><><><><><><><><><><><><>

In [65]:
bol = arr2 > 50

In [66]:
arr2[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr2[arr2 > 50]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
arr2[arr2 < 10]

array([], dtype=int64)

In [77]:
arr2[arr2 > 10]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [78]:
arr2[(arr2 >10) & (arr2 < 30)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [79]:
arr2[(arr2 >10) & (arr2 < 30)].shape

(19,)

In [80]:
arr2[(arr2 >10) & (arr2 < 30)].reshape(3,3)

ValueError: cannot reshape array of size 19 into shape (3,3)

In [81]:
arr2[(arr2 >10) & (arr2 < 30)].reshape(19,1)

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [82]:
arr2[np.logical_and((arr2 >10),(arr2 < 30))]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [83]:
#np.logical_and é mais eficiente que a preposição com &